### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by malcolm-kee** [malcolm-kee/kl-react#10]
Well, just because we can.

Since we using `theme-ui`, see this https://theme-ui.com/color-modes

**Comment by tlcheah2** [comment]
Hi @malcolm-kee ,

I would like to give this a try too.

**Comment by malcolm-kee** [comment]
@tlcheah2 let me add you as contributor so we can work in one of the branch within the repo. That would allows us to preview.

**Comment by malcolm-kee** [comment]
Closed with #36
